### ISSUE TITLE
drf-spectacular compatibility

### ISSUE THREAD

**Issue by MVKozlov** [Pithikos/rest-framework-roles#10]
django 5.0.3
djangorestframework 3.15.0
rest-framework-roles 1.0.5
drf-spectacular 0.27.1

Old code, new issue:
``` python
def is_test(request, view):
    return True

ROLES = {
    # Django out-of-the-box
    'admin': is_admin,
    'user': is_user,
    'anon': is_anon,

    # Some custom role examples
    'test': is_test,
}


class UserProfileView(views.APIView):
#    permission_classes = [permissions.IsAuthenticated]
    view_permissions = {
        'get': { 'test': True },
        'options': { 'test': True },
    }
    def get(self, request: Request, format=None):
        """
        Return a current user.
        """
        serializer = UserSerializer(request.user, context={'request': request})
        return Response(data=serializer.data)
```

_Description_ for method api with enabled `view_permissions` 
return `A wrapped view is the view that was explicitly mentioned in view_permissions, hence it shall ALWAYS check for permissions.`
instead of `Return a current user.`

**Comment by Pithikos** [comment]
Where are you seeing this? In the browseable API?

Essentially you're seeing the `docstring` for the monkey-patched view: https://github.com/Pithikos/rest-framework-roles/blob/master/rest_framework_roles/patching.py#L69-L79

I think this would simply to patch `__doc__`  but would be helpful to be able and reproduce the issue

**Comment by Pithikos** [comment]
@MVKozlov  OK, this fix was simple. Note I didn't try with `drf-spectacular` but the fix is generic - preserving the docstring from the patched method, so it should just work. 

Use the updated version: `rest-framework-roles==1.0.6`

**Comment by MVKozlov** [comment]
Еhis was visible in yaml output and Browsable API

Thanks, the fix works!
